name = "BinPacker"
uuid = "861cb9c3-f70e-438f-a3f0-99158dd8674e"
authors = ["Michael Fiano <mail@mfiano.net> and contributors"]
version = "0.1.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1.8"
